export const StatesMaster = [
  { State: "Andhra Pradesh", Country: "India" },
  { State: "Arunachal Pradesh", Country: "India" },
  { State: "Assam", Country: "India" },
  { State: "Bihar", Country: "India" },
  { State: "Chhattisgarh", Country: "India" },
  { State: "Goa", Country: "India" },
  { State: "Gujarat", Country: "India" },
  { State: "Haryana", Country: "India" },
  { State: "Himachal Pradesh", Country: "India" },
  { State: "Jammu and Kashmir", Country: "India" },
  { State: "Jharkhand", Country: "India" },
  { State: "Karnataka", Country: "India" },
  { State: "Kerala", Country: "India" },
  { State: "Madhya Pradesh", Country: "India" },
  { State: "Maharashtra", Country: "India" },
  { State: "Manipur", Country: "India" },
  { State: "Meghalaya", Country: "India" },
  { State: "Mizoram", Country: "India" },
  { State: "Nagaland", Country: "India" },
  { State: "Odisha", Country: "India" },
  { State: "Punjab", Country: "India" },
  { State: "Rajasthan", Country: "India" },
  { State: "Sikkim", Country: "India" },
  { State: "Tamil Nadu", Country: "India" },
  { State: "Telengana", Country: "India" },
  { State: "Tripura", Country: "India" },
  { State: "Uttarakhand", Country: "India" },
  { State: "Uttar Pradesh", Country: "India" },
  { State: "West Bengal", Country: "India" },
  { State: "Andaman and Nicobar", Country: "India" },
  { State: "Chandigarh", Country: "India" },
  { State: "Dadra and Nagar Haveli", Country: "India" },
  { State: "Daman and Diu", Country: "India" },
  { State: "Delhi", Country: "India" },
  { State: "Lakshadweep", Country: "India" },
  { State: "Puducherry", Country: "India" },
];
